# ONLY PYTHON 3 SUPPORT!
#
# ``conda env create --file environment.yml``
# or
# ``conda env create --name <myEnvName> --file environment.yml``

name: exoticism
channels:
  - sherpa
dependencies:
  - astropy>3.2
  - cairo
  - jinja2
  - matplotlib>3.1
  - pandas
  - scipy>1.2
  - sherpa>4.11
  - pango
  - pip:
    - weasyprint